import { FormEvent, useEffect, useState } from "react";
import { supabase } from "./lib/supabase";

type Result = { id: string; slug: string; title: string; standfirst: string | null; cover_image_url: string | null; published_at: string | null; categories?: { name: string; slug: string } | null };

export default function SearchPage() {
  const initial = new URLSearchParams(window.location.search).get("q") || "";
  const [q, setQ] = useState(initial); const [results, setResults] = useState<Result[]>([]); const [loading, setLoading] = useState(false);
  const search = async (value = q) => { const term=value.trim(); if(!term){setResults([]);return;} setLoading(true); const {data}=await supabase.from("articles").select("id,slug,title,standfirst,cover_image_url,published_at,categories(name,slug)").eq("status","published").or(`title.ilike.%${term}%,standfirst.ilike.%${term}%,body_md.ilike.%${term}%`).order("published_at",{ascending:false}).limit(30); setResults((data||[]) as Result[]); setLoading(false); };
  useEffect(()=>{ if(initial) search(initial); },[]);
  const submit=(e:FormEvent)=>{e.preventDefault(); const term=q.trim(); window.history.replaceState({},"",term?`/search?q=${encodeURIComponent(term)}`:"/search"); search(term);};
  return <main className="min-h-screen bg-black px-5 pb-20 pt-[110px] text-white sm:px-8"><div className="mx-auto max-w-[1120px]"><p className="text-[9px] font-bold uppercase tracking-[.22em] text-white/30">BitBuzz search</p><h1 className="mt-4 max-w-3xl font-serif text-5xl tracking-[-.06em] sm:text-7xl">Find a story.</h1><form onSubmit={submit} className="mt-8 flex max-w-3xl gap-2"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search space, AI, cybersecurity, aviation…" className="min-w-0 flex-1 rounded-full border border-white/15 bg-white/[.04] px-5 py-3.5 text-sm text-white outline-none focus:border-white/35"/><button className="rounded-full bg-white px-6 py-3.5 text-xs font-bold text-black hover:bg-[#ffe600]">Search</button></form><div className="mt-12">{loading?<p className="text-xs text-white/30">Searching the newsroom…</p>:q.trim()&&!results.length?<p className="text-sm text-white/35">No published stories matched “{q}”.</p>:<div className="grid gap-8 md:grid-cols-2">{results.map(a=><a key={a.id} href={`/blog/${a.slug}`} className="group flex gap-5 border-b border-white/10 pb-7"><div className="h-28 w-40 shrink-0 overflow-hidden bg-white/[.03]">{a.cover_image_url&&<img src={a.cover_image_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>}</div><div><p className="text-[8px] font-bold uppercase tracking-[.16em] text-[#83adff]">{a.categories?.name||"BitBuzz"}</p><h2 className="mt-2 font-serif text-2xl leading-none tracking-[-.04em] group-hover:text-white/65">{a.title}</h2>{a.standfirst&&<p className="mt-2 line-clamp-2 text-[11px] leading-5 text-white/35">{a.standfirst}</p>}</div></a>)}</div>}</div></div></main>;
}
